yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', (views.index), name='index'),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    )
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include(
        'posts.urls',
        namespace='posts')
    ),
    path('admin/', admin.site.urls),
    path('auth/', include(
        'users.urls',
        namespace='users')
    ),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='текст поста',
        help_text='напишите то о чем думаете'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа к которой будет '
                  'относиться пост, необязательно'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        help_text='Добавьте изображиние',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        help_text='Придумайте название для сообщества'
    )
    slug = models.SlugField(
        max_length=200,
        unique=True,
        verbose_name='Уникальная ссылка на группу',
        help_text='Можно задать любой адресс, главное '
                  'что бы он не был занят другим пользователем'
    )
    description = models.TextField(
        verbose_name='Описания сообщества',
        help_text='Тут могут быть правила, описания группы и т.д.'
    )

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Коментируемый пост',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор комментария',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='comments',
        help_text='добавляется автоматически'
    )
    text = models.TextField(
        verbose_name='коментарий к посту',
        help_text='выскажите своё мнение'
    )
    created = models.DateTimeField(
        verbose_name='Дата публикации',
        help_text='добавляется автоматически',
        auto_now_add=True
    )

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Подписчик',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_following'
            ),
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = (
            'text',
            'group',
            'image',
        )


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = (
            'text',
        )

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def paginator(queryset, request):
    paginator = Paginator(queryset, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    posts = Post.objects.all()
    page_obj = paginator(posts, request)
    template = 'posts/index.html'
    context = {
        'posts': posts,
        'page_obj': page_obj
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginator(posts, request)
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = paginator(posts, request)
    template = 'posts/profile.html'
    context = {
        'author': author,
        'posts': posts,
        'page_obj': page_obj
    }
    follow_not_author = (
        request.user.is_authenticated
        and (request.user.username is not author.username)
    )
    if follow_not_author:
        following = Follow.objects.filter(
            author=author,
            user=request.user
        )
        context['following'] = following
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    template = 'posts/post_detail.html'
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    template = 'posts/create_post.html'
    context = {
        'form': form
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id, author=request.user)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save()
        return redirect('posts:post_detail', post_id=post.pk)
    template = 'posts/update_post.html'
    context = {
        'form': form,
        'post': post
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    user = request.user
    authors = user.follower.values_list('author', flat=True)
    posts = Post.objects.filter(author__id__in=authors)
    page_obj = paginator(posts, request)
    template = 'posts/follow.html'
    context = {
        'posts': posts,
        'page_obj': page_obj
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    following = Follow.objects.filter(user=user, author=author)
    following.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}
  Создать пост
{% endblock %}
{% block content %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Новый пост
            </div>
            <div class="card-body">
              <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
              {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Текст поста
                    <span class="required text-danger" >*</span>
                  </label>
                  {{ form.text|addclass:"form-control" }}
                  <small id="id_text-help" class="form-text text-muted">
                    {{ form.text.help_text }}
                  </small>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_group">
                    Группа
                  </label>
                  <select name="group" class="form-control" id="id_group">
                    {% for group in form.group %}
                      {{ group }}
                    {% endfor %}
                  </select>
                  <small id="id_group-help" class="form-text text-muted">
                    {{ form.group.help_text }}
                  </small>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_image" >
                    Картинка
                  </label>
                  {{ form.image|addclass:"form-control" }}
                  <small id="id_image-help" class="form-text text-muted">
                    {{ form.image.help_text }}
                  </small>
                </div>
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    Добавить
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}
  Твои подписки
{% endblock %}
{% block heading %}
  <h1>Последние обновления авторов на которых ты подписан</h1>
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'posts/includes/posts_list.html' %}
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
  Записи cообщества {{ group }}
{% endblock %}
{% block heading %}
  <h1>{{ group }}</h1>
{% endblock %}
{% block content %}
  <p>
    {{ group.description }}
  </p>
  {% for post in page_obj %}
    {% include 'posts/includes/posts_list.html' %}
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load cache %}
{% block title %}
  Главная страница
{% endblock %}
{% block heading %}
  <h1>Последние обновления на сайте</h1>
{% endblock %}
{% block content %}
  {% cache 20 content request.user with page_obj %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'posts/includes/posts_list.html' %}
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  {% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Пост {{ post|truncatechars:30 }}
{% endblock %}
{% block content %}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:'d E Y' }}
          </li>
          {% if post.group != None %}  
            <li class="list-group-item">
              Группа: {{ post.group }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя
            </a>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора: <span > {{ post.author.posts.count }} </span>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaks }}
        </p>
        {% if request.user == post.author %}
          <div class="d-flex justify-content-end">
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post_id=post.pk %}">
              Редактировать
            </a>
          </div>
        {% endif %}
      </article>
      {% include 'posts/includes/comments.html' %}
    </div>
  </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  Профайл пользователя {{ author }}
{% endblock %}
{% block heading %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ posts.count }} </h3>
    {% if request.user.username != author.username %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
  </div>
{% endblock %}
{% block content %}
  {% for post in page_obj %}
    {% include 'posts/includes/posts_list.html' %}
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/update_post.html
{% extends "base.html" %}
{% block title %}
  Редактировать пост
{% endblock %}
{% block content %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Редактировать пост
            </div>
            <div class="card-body">
              <form method="post" action="{% url 'posts:post_edit' post_id=post.pk %}" enctype="multipart/form-data">
              {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Текст поста                  
                    <span class="required text-danger" >*</span>
                  </label>
                    {{ form.text }}
                  <small id="id_text-help" class="form-text text-muted">
                    Текст нового поста
                  </small>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_group">
                    Group
                  </label>
                  <select name="group" class="form-control" id="id_group">
                    {% for group in form.group %}
                      {{ group }}
                    {% endfor %}
                  </select>
                  <small id="id_group-help" class="form-text text-muted">
                    Группа, к которой будет относиться пост
                  </small>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_image">
                    Картинка
                    <span class="required text-danger" >*</span>
                  </label>
                  {{ form.image }}
                  <small id="id_image-help" class="form-text text-muted">
                    {{ form.image.help_text }}
                  </small>
                </div>
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    Сохранить
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}